name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - renovate/*
      - ci/update-packages

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux]
        include:
          - system: x86_64-linux
            runs-on: ubuntu-24.04
            arch: amd64
          - system: aarch64-linux
            runs-on: ubuntu-24.04-arm
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Nix
        uses: DeterminateSystems/determinate-nix-action@2be1df9ed6cfd12d52bfbba7af79472420fa5299 # v3.18.0
        with:
          extra-conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Set up Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Run flake checker
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12

      - name: Run flake checks
        run: nix flake check --accept-flake-config
