name: Update packages
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Nix
        uses: DeterminateSystems/determinate-nix-action@v3.17.1
        with:
          extra-conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Set up Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run update script
        run: nix run .#update-packages

      - name: Check the flake
        run: nix flake check

      - name: Create PR if there are changes
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          commit-message: "Update packages"
          title: "Update packages"
          body: "This PR updates the package versions and hashes."
          branch: ci/update-packages
